FROM centos:6
MAINTAINER Yasushi Kobayashi <ptpadan@gmail.com>

RUN yum -y update && \
    yum -y install epel-release && \
    yum -y install ansible
RUN ansible-galaxy install YasushiKobayashi.newrelic

WORKDIR /ansible
COPY ./ /ansible
RUN ansible-playbook -i docker/hosts newrelic.yml
RUN ansible-playbook -i docker/hosts main.yml
